###
# Copyright (2019) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
---
# configure ntp

- name: Open ports in the firewall
  become: true
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    "{{ dhcpd_ports }}"

- name: Install DHCP package
  become: true
  package: 
    name: dhcp
    state: present

- name: Retrieve the MAC Address of all Openshift nodes
  delegate_to: localhost
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    folder: "{{ datacenter }}/vm/{{ cluster_name }}"
    name: "{{ item }}"
  with_items:
    - "{{ groups.rhcos }}"
  register: vms_facts

- name: Create dhcp.conf 
  become: true
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: restart DHCP

